import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { GlobeProvider } from "../contexts/GlobeContext";
import { Inter } from "next/font/google";
import "./globals.css";
import AnimatedBackground from "@/components/animations/AnimatedBackground";
import Globe from "@/components/animations/Globe";
import Header from "@/components/layout/Header";
import GlobeController from "@/components/animations/GlobeController";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full bg-black text-white overflow-hidden relative">
          <GlobeProvider>
            <GlobeController />
            {/* Persistent background */}
            <div className="relative z-10">
              <AnimatedBackground />
              <Globe />
            </div>
            <Header />
            <div className="relative mt-20 z-20">{children}</div>
          </GlobeProvider>
        </div>
      </body>
    </html>
  );
}
