import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { GlobeProvider } from "../contexts/GlobeContext";
import { Inter } from "next/font/google";
import "./globals.css";
import AnimatedBackground from "@/components/animations/AnimatedBackground";
import Globe from "@/components/animations/Globe";
import Header from "@/components/layout/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen w-full bg-black text-white overflow-hidden relative">
          <GlobeProvider>
            {/* Persistent background */}
            <div className="relative z-10">
              <AnimatedBackground />
              <Globe />
            </div>
            <Header />

            <div className="relative mt-20 z-20">{children}</div>
          </GlobeProvider>
        </div>
      </body>
    </html>
  );
}
